/*****************************************************
 *
 *  Krain
 */

#include "builder/timeline.hpp"
#include "builder/step.hpp"
using namespace GMAM;
using namespace GMAM::builder;

Timeline::Timeline() {}

void Timeline::append(Step *s) {
    steps.push_back(s);
}

void Timeline::debug_print(std::ostream &os) {
    os << "[";
    for (auto i : steps) {
        i->debug_print(os);
    }
    os << "]" << std::endl;
}

void Timeline::final_print(std::ostream &os) {
    final_print_intro(os);
    for (auto i : steps) {
        i->final_print(os);
    }
    final_print_outro(os);
}

void Timeline::final_print_intro(std::ostream &os) {
    os << "<!--This Document is generated by GameMaker, if you edit it by hand then you do so at your own risk!-->" << std::endl;
    os << "<timeline>" << std::endl;
}

void Timeline::final_print_outro(std::ostream &os) {
    os << "</timeline>" << std::endl;
}